### ISSUE TITLE
bro its showing virus 

### ISSUE THREAD

**Issue by NExxUss-07** [EndlessGod/ValoPy#1]
its showing virus and also Mcafee is deleting this again and again 
![image](https://user-images.githubusercontent.com/98755775/152143791-6ecb8216-e544-4db4-b4da-44b7c43ec1c8.png)

**Comment by Phar0ss** [comment]
hi, this "Third-party Software" although it is not a virus, it can detect it as a virus.There is no protection in the exe, it is packaged with pyinstaller and its source code is accessible.

**Comment by NExxUss-07** [comment]
ok bro if u are saying ill close the firewall
